name: Build and Test in Debug and Release Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Build project
        run: dotnet build Fingerprint.Unifications/Fingerprint.Unifications.csproj --configuration ${{ matrix.configuration }}
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ matrix.configuration }}
          path: |
            Fingerprint.Unifications/bin/${{ matrix.configuration }}/**/*
            Fingerprint.Unifications/obj/${{ matrix.configuration }}/**/*
          retention-days: 7

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Run tests
        run: dotnet test Fingerprint.UnificationsTests/Fingerprint.UnificationsTests.csproj --configuration ${{ matrix.configuration }}

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    needs: [build, test]
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-output-${{ matrix.configuration }}
        path: ./downloaded-artifacts/${{ matrix.configuration }}

    - name: List downloaded files
      run: ls -la ./downloaded-artifacts/${{ matrix.configuration }}/

    - name: Upload final artifacts (${{ matrix.configuration }})
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}-final-build
        path: ./downloaded-artifacts/${{ matrix.configuration }}/
        retention-days: 30
