name: Build and Test in Debug and Release Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Build project
        run: dotnet build Fingerprint.Unifications/Fingerprint.Unifications.csproj --configuration ${{ matrix.configuration }}
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files-${{ matrix.configuration }}
          path: /dist
          retention-days: 7

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Run tests
        run: dotnet test Fingerprint.UnificationsTests/Fingerprint.UnificationsTests.csproj --configuration ${{ matrix.configuration }}

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/
          
      - name: List downloaded files
        run: ls -la dist/
        
      - name: Deploy
        run: ./deploy.sh